# Generated by Django 4.2.7 on 2023-11-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Notebook',
        ),
    ]
