# Generated by Django 4.2.7 on 2023-11-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_book_delete_copybook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='Product',
        ),
    ]
