# Generated by Django 4.2.7 on 2023-11-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pagination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagination',
            new_name='Phone',
        ),
    ]
